module.exports = {
    semi: true,
    singleQuote: true,
    jsxSingleQuote: true,
    tabWidth: 4,
    bracketSpacing: true,
    printWidth: 120,
    bracketSameLine: false,
    trailingComma: 'all',
    arrowParens: 'always',
    singleAttributePerLine: true,
    endOfLine: 'lf',
    importOrder: [
        '<BUILTIN_MODULES>',
        '',
        '<THIRD_PARTY_MODULES>',
        '',
        '<TYPES>',
        '',
        '^~/(.*?)',
        '',
        '^(?!.*[.]css$)[./].*$',
        '',
        '.css$',
    ],
    importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
    plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
};
